// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDijEDKYthzBuLD7ONEkxS73kwYjTCVzPg',
    appId: '1:839996059413:android:95f252fa49963388e6831c',
    messagingSenderId: '839996059413',
    projectId: 'moveo-app-333ff',
    databaseURL: 'https://moveo-app-333ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'moveo-app-333ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsvxgPYks9PW-cOBnR-mdegaW-U63l3_Q',
    appId: '1:839996059413:ios:48437fd55143fa51e6831c',
    messagingSenderId: '839996059413',
    projectId: 'moveo-app-333ff',
    databaseURL: 'https://moveo-app-333ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'moveo-app-333ff.appspot.com',
    iosClientId: '839996059413-m0rrmd4kok54iuct06fcbo1h2299eus3.apps.googleusercontent.com',
    iosBundleId: 'com.example.moveoApp',
  );
}
